### ISSUE TITLE
Nothing to click -- to start a session

### ISSUE THREAD

**Issue by cbitterfield** [google/chrome-ssh-agent#12]
I tried this on Windows 10 and OSX 10.13. Click on the button, load the key and that's all it does. 
There is no link in the window as shown to start a session
![screen shot 2018-11-27 at 8 42 47 pm](https://user-images.githubusercontent.com/11802951/49123029-0566de80-f285-11e8-80a2-63475630a718.png)

**Comment by iamhsa** [comment]
I think you should use chrome-ssh-agent in addition of [Secure Shell extension](https://chrome.google.com/webstore/detail/secure-shell-extension/iodihamcpbpeioajjeobimgagajmlibd) 
As it's indicated in README :

> 4. When creating a new connection in the Secure Shell extension, add
   `--ssh-agent=eechpbnaifiimgajnomdipfaamobdfha` to "SSH Relay Server
   Options" field to indicate that it should use the SSH Agent for keys.

**Comment by ralimi** [comment]
Yes, that's right. This is only an SSH agent for holding keys, and not the SSH client itself.
