### ISSUE TITLE
ssh agent not used for WASM ssh connections

### ISSUE THREAD

**Issue by cshelton1409** [google/chrome-ssh-agent#136]
When the secure shell extension runs as WASM code instead of PNACL code, which it seems to do occasionally, the ssh agent code does not work to provide authentication for the ssh connection.  This results in being prompted for a password, when the public key is not offered to the remote ssh server.  

I use the secure shell extension regularly, as well as the ssh-agent extension to provide authentication.  Whenever the secure shell tries to run its WASM version, the ssh agent code is not running.  I am requesting the use of this extension by adding the following to the ssh relay server option box:
`--ssh-agent=eechpbnaifiimgajnomdipfaamobdfha
`

**Comment by ralimi** [comment]
Hi @cshelton1409  - I'm looking to reproduce this.   I've tried a few times, but I still get it running in the PNACL mode.  Any idea how to force WASM?

@vapier do you have thoughts here?

**Comment by vapier** [comment]
use `--ssh-client-version=wasm` in the relay server field to force wasm usage

**Comment by ralimi** [comment]
Thanks @vapier .  @cshelton1409  - I have attempted to reproduce this, but can't - it seems to work for me consistently.

One thing to try might be this:
1. Go to "manage extensions" and select the Chrome SSH Agent extension
2. Click on the "service worker" option under Inspect Views. This should bring up the console under Chrome's developer tools
3. Attempt to connect using the SSH client.

When you do this, do you see log messages going by that would indicate the SSH Agent is being used?

**Comment by matthew-0-1** [comment]
This might be the same issue as:

https://issuetracker.google.com/263148145 `wassh: --ssh-agent with SSH Agent extension is flaky`

**Comment by matthew-0-1** [comment]
When I encounter this symptom and unexpectedly get prompted for a password, in most or possibly all cases password authentication doesn't work either, authentication fails again even with a correctly typed valid password.

It's as if there is continued data loss or corruption between `wassh` and the SSH server regardless of authentication method, until closing the connection attempt and trying again.

**Comment by cshelton1409** [comment]
I tried to reproduce the issues that I was seeing a couple of days ago, and could not do so.  The extension is working just fine now.  
The only time that I ran into this recently was after the updated version was installed, and I was prompted for my password since the upgrade of the extension lost its stored agent.  This is basically expected during updates, I think.

**Comment by ralimi** [comment]
Thanks @matthew-0-1 and @cshelton1409 .  Based on observations, its sounding like this might be something with the WASM version itself.

As a suggestion, we can keep this open for a couple of months to see if any more information comes to light, and then we can close it if not reproducible.
