### ISSUE TITLE
CrOS Terminal app is not allowlisted

### ISSUE THREAD

**Issue by matthew-0-1** [google/chrome-ssh-agent#159]
The ChromeOS / ChromiumOS builtin Terminal app gained SSH capability many releases ago, built on the same libraries as the Secure Shell extension.

Per Terminal app maintainer, it does not have a manifest ID, however it should be possible to allowlist using:

```
  "externally_connectable": {
    "matches": [
      "chrome-untrusted://terminal/html/terminal_ssh.html*"
    ]
  }
```

I'll send a pull request for this shortly.

**Comment by vapier** [comment]
I would allow all terminal pages, not just that one

**Comment by matthew-0-1** [comment]
Are you thinking `"chrome-untrusted://terminal/html/*"` or `"chrome-untrusted://terminal/*"` ?

**Comment by vapier** [comment]
def at least the former. maybe the latter.

I don't think we'd ever have "untrusted" pages executing in this context. if we did, we'd have bigger problems.

**Comment by joelhockey** [comment]
Terminal app has a few main pages under chrome-untrsted://terminal/html:
terminal_ssh.html*: all ssh sessions
terminal.html*: home page and terminal sessions to local VMs
terminal_settings.html: settings page

It should be sufficient to allowlist only `chrome-untrusted://terminal/html/terminal_ssh.html*`, but I also think it is fine to set it to `chrome-untrusted://terminal/*`.  I tend to set minimal permissions for this sort of thing by default, but the browser security model is mostly based around origins, so they are mostly equivalent.

Note: We have no intention to change these URLs, but we also make no gurantees that we wont.

**Comment by vapier** [comment]
yeah, i'm thinking future proof here.  like mosh.

**Comment by matthew-0-1** [comment]
I went with `"chrome-untrusted://terminal/*"` in the initial pull request because it seems most equivalent to the existing manifest ID based permissions.  And also the most future proof. :-)
