### ISSUE TITLE
no support for sftp get of binary files ?

### ISSUE THREAD

**Issue by aerndavid** [google/chrome-ssh-agent#16]
Looks like the sftp feature only supports ASCII.

If you try to sftp get a .tar or .zip file it gets corrupted.

**Comment by vapier** [comment]
what does SFTP have to do with this ssh-agent extension ?  the two are unrelated.

**Comment by aerndavid** [comment]
Yup. That's because I've filed it in the wrong place. Should have been for hterm not ssh-agent. Sorry.
