### ISSUE TITLE
Simply not work on chrome Version 75.0.3770.100 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by yuanzhel** [google/chrome-ssh-agent#17]
I provide my host machine private key and load it, add the "SSH Relay Server Options" field.
But when i login to the server, it still ask for my password.

**Comment by yuanzhel** [comment]
Finally solved by add authorized_keys on my remote machine, and import both id_ras and id_rsa.pug to nassh. More info can be found in https://chromium.googlesource.com/apps/libapps/+/master/nassh :-)

**Comment by zengdd-pro** [comment]
> 最终通过在我的远程计算机上添加authorized_keys解决了，并将id_ras和id_rsa.pub都导入了nassh。可以在https://chromium.googlesource.com/apps/libapps/+/master/nassh :-)中找到更多信息。

How to import the key and connect without secret?
Are there detailed steps?
