### ISSUE TITLE
Does not work with chrome-extensions for opera

### ISSUE THREAD

**Issue by rmstock2** [google/chrome-ssh-agent#18]
A popular method to work with chrome extensions from Opera is to first add  chrome-extensions from 
https://addons.opera.com/en/extensions/details/install-chrome-extensions/
after that one can add chrome-ssh-agent. I've done this but the add-on does not show the "Open Secure Shell" button : 

![SSH Agent for Google Chrome tm - Opera](https://user-images.githubusercontent.com/44626257/60734532-8b03e880-9f50-11e9-80d8-098e7992d9a3.png)

**Comment by ralimi** [comment]
This extension wasn't intended to support Opera; it was intended to work specifically with the [Secure Shell Chrome extension](https://chrome.google.com/webstore/detail/secure-shell/iodihamcpbpeioajjeobimgagajmlibd).

Do you use that extension as your ssh client via Opera?

**Comment by ralimi** [comment]
This extension doesn't provide a Secure Shell client itself; it relies on a different extension for that.

Please let me know if I've misunderstood the request here.
