### ISSUE TITLE
Does not work with ECDSA keys

### ISSUE THREAD

**Issue by srdjanrosic** [google/chrome-ssh-agent#19]
I'm able to add the key through the UI, but when trying to 'load' it, it keeps asking for a password, even when key is unencrypted.

If I use `ssh-add` on a remote session, the key is added to the agent, but is seems like the key is lost later / not synced.

These keys can be generated using `ssh-keygen -t ecdsa -b 521`, as one would expect.

**Comment by srdjanrosic** [comment]
Checked, and it doesn't work with 256bit (default) ecdsa keys either:

exact error message when entering a empty passphrase (key is unencrypted, so it shouldn't be asking for a passphrase in the firstplace) is "failed to load key: failed to parse private key: ssh: unhandled key type"

**Comment by srdjanrosic** [comment]
```
$ grep -nir 'unhandled key'
vendor/github.com/ScaleFT/sshkeys/parse.go:214:         return nil, errors.New("sshkeys: unhandled key type")
vendor/golang.org/x/crypto/ssh/keys.go:1076:            return nil, errors.New("ssh: unhandled key type")
```

So that's where the error message comes from, interesting ...

Looks like these vendored libraries were last updated in 2018...
...meanwhile, looking at upstream change history, there does seem to be support ECDSA as well as encrypted keys, see:

https://github.com/golang/crypto/commits/master/ssh/keys.go

---

It looks like these vendored libraries just need a version bump ... (and maybe some fixing since it wasn't updated in a while).

**Comment by zengdd-pro** [comment]
I also need help.
I use ssh-keygen -t rsa to generate a key without a password.
After importing to SSH Agent for Google Chrome, I still prompt for a password when I connect.
Please tell me how to use this SSH Agent for Google Chrome.

**Comment by ralimi** [comment]
@zengdd-pro This issue is specifically for support of ECDSA keys. Can you open a different issue?
