### ISSUE TITLE
SSH Agent Forwarding?

### ISSUE THREAD

**Issue by maxamillion** [google/chrome-ssh-agent#2]
This is not really an issue, but maybe a feature request or just a request for documentation. I was curious if it's possible to do ssh agent forwarding with this?

If so, how?

If not, is that something that could be added?

Thank you!

**Comment by ralimi** [comment]
SSH Agent forwarding should work.  When creating an SSH connection in Chrome's Secure Shell, be sure to pass '-A' in the "SSH Arguments".

**Comment by maxamillion** [comment]
@ralimi I didn't even think to try it, I couldn't find it in the documentation and assumed it wasn't available. This is amazing, thank you!
