### ISSUE TITLE
ed25519 keys don't load

### ISSUE THREAD

**Issue by jdhutchin** [google/chrome-ssh-agent#32]
My ed25519 ssh key doesn't seem to load.  I think this started with the Aug 12 2022 release- this key has worked fine for a long time but now fails.

Steps:
- Open extension and press "load" for an ed25519 key (public key starts with ssh-ed25519)
- Enter correct passphrase

Expected:
- Key loads.  This has worked correctly for a long time.

Actual:
- Load fails with an error message "failed to load key: failed to decrypt key: key marshalling failed: x509: unknown key type while marshaling PKCS#8: *ed25519.PrivateKey"

I tried entering the wrong passphrase and got a different error ("failed to load key: failed to decrypt key: failed to parse private key: x509: decryption password incorrect") so I'm pretty sure my passphrase is correct.

This is on a ChromeOS device.
- Chrome Version 104.0.5112.83 (Official Build) (64-bit)
- Extension version 0.0.20

**Comment by ralimi** [comment]
Thanks for reporting!  This was resolved in #28, but the new version is still pending review in the webstore.  I'll reopen that one for clarity until it is finally released.
